import { readFileSync, writeFileSync } from 'fs';
import { load } from 'js-yaml';
import { join } from 'path';

export default function script() {

  const configPath = join(__dirname, '../../readme-template.yml');
  const readmePath = join(process.env.GITHUB_WORKSPACE, 'tmp/new-README.md');
  const changelogPath = join(process.env.GITHUB_WORKSPACE, 'tmp/updated-changelog.md');

  const config = load(readFileSync(configPath, 'utf-8'));
  let changelogContent = changelogPath ? readFileSync(changelogPath, 'utf-8') : '';

  // Process changelogContent to remove the first line and add "## Changelog"
  if (changelogContent) {
    const changelogLines = changelogContent.split('\n');
    changelogLines.shift(); // Remove the first line
    changelogContent = `## Changelog\n${changelogLines.join('\n')}`;
  }

  const readmeContent = `
  <!--
  This README is autogenerated. Do not make modifications directly to this file.
  Changes should be made to the readme-template.yml file and the generate-readme.js script.
  -->

  # ${config.readme.title}

  ${config.readme.summary}

  ${config.readme.commands}
  ## Known Issues
  ${config.readme.known_issues.map(issue => `- ${issue}`).join('\n')}

  ## Owner Maintainers
  ${config.readme.owner_maintainers.map(owner => `- ${owner}`).join('\n')}
  `;

  writeFileSync(readmePath, readmeContent.trim(), 'utf-8');
}