apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-buddy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: event-buddy
  template:
    metadata:
      labels:
        app: event-buddy
    spec:
      containers:
      - image: ghcr.io/petercort/event-buddy:latest
        name: event-buddy
        ports:
        - containerPort: 80
