name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      
env:
  IMAGE_NAME: event-buddy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Build image
      run: docker build --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" .

    - name: Get the latest release
      id: get_latest_release
      uses: actions/github-script@v6
      with:
        script: |
          const latestRelease = await github.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          core.setOutput('tag_name', latestRelease.data.tag_name);

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=${{ steps.get_latest_release.outputs.tag_name }}
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION

    - name: Update values.yaml
      run: |
        cd config
        sed -i 's|APP_VERSION:.*|APP_VERSION: '${{  steps.get_latest_release.outputs.tag_name }}'|' event-buddy-values.yaml 
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'no-reply@github.com'
        git add values.yaml
        git commit -m "Update values.yaml"
        git push

    - name: Create Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Event Buddy Release - ${{ steps.get_latest_release.outputs.tag_name }}
        tag: ${{ steps.get_latest_release.outputs.tag_name }}