name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      
env:
  IMAGE_NAME: fbf-buddy
  RESOURCE_GROUP: peter-corp-rg
  CONTAINER_APP_NAME: discord-buddy

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get release version
      id: release-version
      run: |
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Build image
      run: docker build --build-arg KEY_VAULT_NAME=${{ secrets.KEY_VAULT_NAME }} 
        --build-arg AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} 
        --build-arg AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }} 
        --build-arg AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }} 
        --file Dockerfile 
        --tag $IMAGE_NAME 
        --label "runnumber=${GITHUB_RUN_ID}" 
        -t fbf-buddy . 
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image with multiple tags
      env: 
        VERSION: ${{ steps.release-version.outputs.VERSION }}
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        # Tag the image with both the version and 'latest'
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:latest

        # Push both tags
        docker push $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:latest

    - name: Create Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ steps.release-version.outputs.VERSION }}
        tag: ${{ steps.release-version.outputs.VERSION }}
        
    - name: Azure login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        client-id: ${{ secrets.AZURE_DEPLOY_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Deploy public GHCR image to Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: $CONTAINER_APP_NAME
        resourceGroup: $RESOURCE_GROUP
        imageToDeploy: ghcr.io/${{ github.repository_owner }}/$IMAGE_ID:latest
